.github/workflows/all.testWithRpc.yml
web/package.json

Test actions web

---

changeProyectsReferencesToRepo.sh

script to change references

---

.github/workflows/all.publish.yml

publish action

---

.github/workflows/all.publish.yml

Auth into npm when publishing

---

.github/workflows/all.publish.yml

add npmrc to actions file

---

.github/workflows/all.publish.yml

publlish public

---

sdk/src/app/usecase/command/stablecoin/operations/cashin/CashInCommandHandler.ts
sdk/src/domain/context/stablecoin/StableCoin.ts
sdk/src/domain/context/stablecoin/error/InitSupplyInvalid.ts
sdk/src/domain/context/stablecoin/error/MaxSupplyOverLimit.ts
web/src/views/StableCoinCreation/OptionalDetails.tsx

Feature/kenny #280

---

FACTORY_VERSION.md
cli/package.json
contracts/package.json
defenders/package.json
hashconnect/lib/package.json
package.json
sdk/package.json
web/package.json

New relation between Stablecoin Studio version and factory's contract id

---

FACTORY_VERSION.md
cli/package.json
contracts/package.json
contracts/test/rescuable.ts
defenders/package.json
hashconnect/lib/.npmignore
hashconnect/lib/package-lock.json
hashconnect/lib/package.json
package.json
sdk/__tests__/port/in/Proxy.test.ts
sdk/package.json
sdk/src/port/out/hs/blade/BladeTransactionAdapter.ts
sdk/src/port/out/rpc/RPCTransactionAdapter.ts
web/package-lock.json
web/package.json
web/src/Router/NamedRoutes.ts
web/src/Router/Router.tsx
web/src/Router/RoutesMappingUrl.ts
web/src/components/ModalWalletConnect.tsx
web/src/i18n.ts
web/src/interfaces/IMirrorRPCNode.ts
web/src/layout/sidebar/Sidebar.tsx
web/src/services/SDKService.ts
web/src/store/slices/walletSlice.ts
web/src/translations/en/appSettings.json
web/src/translations/en/global.json
web/src/views/AppSettings/constants.ts
web/src/views/AppSettings/index.tsx
web/src/views/Roles/constants.ts

Sprint 30 2

---

sdk/__tests__/port/in/CustomFees.test.ts
sdk/__tests__/port/out/RPCTransactionAdapter.test.ts
sdk/package-lock.json
sdk/src/domain/context/custodialwalletsettings/DfnsSettings.ts
sdk/src/port/out/hs/hts/custodial/CustodialTransactionAdapter.ts
sdk/src/port/out/hs/hts/custodial/DFNSTransactionAdapter.ts
sdk/src/port/out/hs/hts/custodial/FireblocksTransactionAdapter.ts
web/package-lock.json
web/package.json
web/src/components/Form/FireblocksFormModal.tsx
web/src/components/ModalWalletConnect.tsx

Web is failing to execute test because could not found axios
Changed jest axios path replacement

[Web] axios not found in test

---

.github/workflows/all.publish.yml

fix custodial wallet dependencies

fix pipeline

---

FACTORY_VERSION.md
cli/package.json
contracts/package.json
defenders/package.json
hashconnect/lib/package.json
package.json
sdk/package.json
web/package.json

Updated versions

---

FACTORY_VERSION.md
cli/package-lock.json
cli/package.json
contracts/package-lock.json
contracts/package.json
defenders/package.json
hashconnect/lib/package-lock.json
hashconnect/lib/package.json
sdk/package-lock.json
sdk/package.json
web/package-lock.json
web/package.json

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 📝
Fixes # (issue) 🛠️
Fixes # [1060](https://github.com/hashgraph/stablecoin-studio/issues/1060) 🛠️
Fixes # [1061](https://github.com/hashgraph/stablecoin-studio/issues/1061) 🛠️
- **Code Comments** (I have commented my code, particularly in …

custodian library updated in sdk

---

web/src/views/StableCoinCreation/ManagementPermissions.tsx
web/src/views/StableCoinCreation/Review.tsx

Fixes #1072 🛠️
- **Local Test Pass** (New and existing unit tests pass …

KYC bug fixed

---

.husky/commit-msg
.husky/pre-commit
backend/package-lock.json
backend/src/utils/utils.ts
cli/package-lock.json
commitlint.config.ts
contracts/package-lock.json
hashconnect/lib/package-lock.json
package.json
sdk/package-lock.json
web/package-lock.json

Check if signoff message and update husky version
- **Local Test Pass** (New …

Add DCO pre-commit check

---

backend/README.md
backend/package.json
backend/src/scripts/deleteAllDBTransactions.ts
backend/src/transaction/transaction.service.ts
backend/test/transaction/transaction.service.spec.ts

Feat to delete all transactions from DB

feat: script to clean transactions from DB

---

sdk/__tests__/config.ts
sdk/__tests__/port/out/MultiSigTransactionAdapter.test.ts
sdk/__tests__/port/out/OLD_MultiSigTransactionAdapter.test.ts
sdk/src/port/out/backend/BackendAdapter.ts
sdk/src/port/out/hs/multiSig/TransactionDescription.ts

Bugs detected in SDK
Fixes # (issue) 🛠️
- **Local Test Pass** (New and …

backend integration SDK : bugs fixed

---

sdk/src/port/in/StableCoin.ts

Added missing View Models to the SDK
- **Local Test Pass** (New and existing …

fix: view models added

---

sdk/src/app/usecase/command/stablecoin/backend/sign/SignCommandHandler.ts
sdk/src/port/out/hs/HederaTransactionAdapter.ts
sdk/src/port/out/hs/hashpack/HashpackTransactionAdapter.ts
sdk/src/port/out/rpc/RPCTransactionAdapter.ts

Hashpack and Metamask signing issues
- **Local Test Pass** (New and existing …

fix: sdk sign hashpack and metamask

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
backend/src/transaction/dto/get-transactions-response.dto.ts
backend/src/transaction/transaction.controller.ts
backend/test/transaction/transaction.controller.spec.ts
backend/test/utils/utils.spec.ts

The Hedera account ID query param was marked as required in OpenAPI (Swagger) doc.
- Set to not required
- Set default example to testnet not mainnet
- prettier and linter before commiting
- Added the pull reques template to this repo
- …

Hedera account ID not required

---

README.md
sdk/package.json
sdk/scripts/CreateMultisigAccount.ts
sdk/tsconfig.json

Script to create multisig accounts and related documentation
- **Local Test …

docs: multisig doc and script

---

FACTORY_VERSION.md
backend/package-lock.json
backend/package.json
cli/package-lock.json
cli/package.json
contracts/package-lock.json
contracts/package.json
hashconnect/lib/package-lock.json
hashconnect/lib/package.json
package.json
sdk/package-lock.json
sdk/package.json
sdk/src/port/out/hs/blade/BladeTransactionAdapter.ts
sdk/src/port/out/hs/hashpack/HashpackTransactionAdapter.ts
web/README.md
web/package-lock.json
web/package.json
web/src/Router/Router.tsx
web/src/components/ModalWalletConnect.tsx

upgrading Blade connector version to 1.6.1
disabling hashpack from the UI
- …

feat: blade new version integration

---

sdk/src/port/out/hs/HederaTransactionAdapter.ts
sdk/src/port/out/hs/multiSig/MultiSigTransactionAdapter.ts

Fix start date in multisig mode
Fixes # (issue) 🛠️

hotfix: start date multisig

---

FACTORY_VERSION.md
backend/package-lock.json
backend/package.json
cli/package-lock.json
cli/package.json
contracts/package-lock.json
contracts/package.json
hashconnect/lib/package-lock.json
hashconnect/lib/package.json
package.json
sdk/package-lock.json
sdk/package.json
web/package-lock.json
web/package.json

chore: bump version to 1.20.1

---

backend/README.md
backend/src/jobs/autoSubmit.service.ts
backend/src/transaction/dto/update-transaction-request.dto.ts
backend/src/transaction/status.enum.ts
backend/src/transaction/transaction.controller.ts
backend/src/transaction/transaction.service.ts
cli/__tests__/app/service/stablecoin/ListMultiSigTxService.test.ts
cli/__tests__/app/service/stablecoin/ManageMultiSigTxService.test.ts
cli/src/app/service/stablecoin/ListMultiSigTxService.ts
cli/src/app/service/stablecoin/ManageMultiSigTxService.ts
cli/src/domain/stablecoin/MultiSigTransaction.ts
cli/src/resources/config/language.ts
sdk/__tests__/port/out/BackendAdapter.test.ts
sdk/src/app/usecase/command/stablecoin/backend/submit/SubmitCommandHandler.ts
sdk/src/domain/context/transaction/MultiSigTransaction.ts
sdk/src/port/out/backend/BackendAdapter.ts
web/src/constant.ts
web/src/views/MultiSigTransactions/MultisigTransactions.tsx

feat: executed multisig trans status

---

backend/src/transaction/dto/update-transaction-request.dto.ts

fix: backend tests

---

cli/__tests__/app/service/factoryProxy/ImplementationFactoryProxyService.test.ts
cli/__tests__/app/service/factoryProxy/OwnerFactoryProxyService.test.ts

CLI "factory" tests updated
- **Local Test Pass** (New and existing unit …

feat: new cli tests factory

---

cli/__tests__/app/service/commander/CommanderService.test.ts
cli/__tests__/app/service/configuration/SetMirrorNodeService.test.ts
cli/__tests__/app/service/configuration/SetRPCService.test.ts
cli/__tests__/app/service/proxy/ConfigurationProxyService.test.ts
cli/__tests__/app/service/proxy/ImplementationProxyService.test.ts
cli/__tests__/app/service/proxy/OwnerFactoryService.test.ts
cli/__tests__/app/service/utilities/UtilitiesService.test.ts
cli/__tests__/app/service/wizard/NetworkWizardService.test.ts
cli/__tests__/app/service/wizard/WizardService.test.ts
cli/__tests__/domain/language/Language.test.ts
cli/src/app/service/proxy/ConfigurationProxyService.ts
cli/src/app/service/proxy/ImplementationProxyService.ts
cli/src/app/service/proxy/OwnerProxyService.ts
cli/src/app/service/utilities/UtilitiesService.ts
cli/src/app/service/wizard/NetworkWizardService.ts
cli/src/app/service/wizard/WizardService.ts

Fixing cli tests

---

.github/workflows/all.testWithRpc.yml
cli/__tests__/app/service/stablecoin/AssociateStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/BalanceOfStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/BurnStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/CashInStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/DeleteStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/FreezeStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/KYCStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/ListStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/OperationStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/PauseStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/RescueHBARStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/RescueStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/TransfersStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/UpdateStableCoinService.test.ts
cli/__tests__/app/service/stablecoin/WipeStableCoinService.test.ts
cli/__tests__/app/service/utilities/UtilitiesService.test.ts
cli/jest.config.js
cli/package.json
sdk/__tests__/jest-setup-file.ts
sdk/__tests__/port/in/Account.test.ts
sdk/__tests__/port/in/CustomFees.test.ts
sdk/__tests__/port/in/Proxy.test.ts
sdk/__tests__/port/in/Reserve.test.ts
sdk/__tests__/port/in/Roles.test.ts
sdk/__tests__/port/in/StableCoin.test.ts
sdk/__tests__/port/out/RPCTransactionAdapter.test.ts

fix: cli tests stablecoins (1)

---

.github/CODEOWNERS
.github/workflows/all.publish.yml
.github/workflows/all.testWithRpc.yml

Updated workflows with new runner label and added codeowners
Fixes #1170

ci: Updated workflows with new runner label and added codeowners

---

cli/package-lock.json
sdk/src/app/usecase/command/stablecoin/create/CreateCommandHandler.ts
sdk/src/core/Time.ts
sdk/src/port/out/mirror/MirrorNodeAdapter.ts
web/package-lock.json

fix: sdk mirrornode refactored

---

sdk/src/domain/context/hwalletconnectsettings/HWCSettings.ts
sdk/src/port/in/request/ConnectRequest.ts
sdk/src/port/in/request/mapping/RequestMapper.ts
sdk/src/port/out/hs/walletconnect/HederaWalletConnectTransactionAdapter.ts
web/.env.sample
web/src/layout/topbar/TopbarRight.tsx
web/src/services/SDKService.ts

Fix and Improve Hedera Wallet Connect disconnect from UI
Also add icons metadata handling
- **Local Test Pass** (New and existing unit tests pass locally with my changes) ✅
- **Dependency Updates** (Any dependent changes have been merged and …

[BBND-261] Fix and Improve HWC disconnect

---

.github/workflows/all.publish.yml
.github/workflows/all.testWithRpc.yml

Add "contents" persmission
Fixes #1207 
**Checklist**

ci: Add "contents" persmission

---

contracts/contracts/HederaTokenManager.sol
contracts/contracts/Interfaces/IHederaTokenManager.sol
contracts/contracts/StableCoinFactory.sol
contracts/contracts/extensions/Burnable.sol
contracts/contracts/extensions/CashIn.sol
contracts/contracts/extensions/CustomFees.sol
contracts/contracts/extensions/Deletable.sol
contracts/contracts/extensions/Freezable.sol
contracts/contracts/extensions/Interfaces/ICustomFees.sol
contracts/contracts/extensions/KYC.sol
contracts/contracts/extensions/Pausable.sol
contracts/contracts/extensions/Rescuable.sol
contracts/contracts/extensions/Roles.sol
contracts/contracts/extensions/TokenOwner.sol
contracts/contracts/extensions/Wipeable.sol
contracts/contracts/library/KeysLib.sol
contracts/package-lock.json
contracts/package.json
sdk/package-lock.json

feat: added ICustomFee interface

---

web/src/Router/__test__/__snapshots__/Router.test.tsx.snap
web/src/app/__test__/__snapshots__/App.test.tsx.snap
web/src/layout/__test__/__snapshots__/Layout.test.tsx.snap
web/src/layout/sidebar/__test__/__snapshots__/Sidebar.test.tsx.snap
web/src/translations/en/roles.json
web/src/views/Roles/GetAccountsWithRole.tsx
web/src/views/Roles/HandleRoles.tsx
web/src/views/Roles/constants.ts
web/src/views/StableCoinCreation/ManagementPermissions.tsx
web/src/views/StableCoinCreation/Review.tsx
web/src/views/StableCoinCreation/StableCoinCreation.tsx
web/src/views/StableCoinCreation/components/KeySelector.tsx

feat: [BBND-412] add token manager fee schedule

---

cli/package-lock.json
cli/src/app/service/stablecoin/CreateStableCoinService.ts
cli/src/resources/config/language.ts

Also include some `npm audit fix`.

[BBND-416]  [cli] Modify CreateStableCoinService.ts with new logics

---

web/src/layout/sidebar/Sidebar.tsx

fix: show fee management with metamask

---

web/src/views/FeesManagement/index.tsx

fix: fee management permissions

---

web/src/views/FeesManagement/__test__/index.test.tsx

Fix FeeManagement test in web
Fixes #
**Checklist**

fix: web tests

---

backend/src/jobs/autoSubmit.service.ts
backend/src/transaction/transaction.service.ts
backend/src/utils/utils.ts
backend/test/transaction/transaction.service.spec.ts
cli/package-lock.json
sdk/package-lock.json
sdk/package.json
sdk/src/app/usecase/command/stablecoin/backend/sign/SignCommandHandler.ts
sdk/src/port/out/hs/walletconnect/HederaWalletConnectTransactionAdapter.ts
web/package-lock.json

fix: hwc dapp signature

---

.github/CODEOWNERS

Changes devops-ci to platform-ci

chore: Update codeowners with new team name platform-ci

---

package.json

**Details**:
Needed to add scope to package.json name
**Related Issue(s)**:
Fixes #1239

chore: Add hashgraph scope to package.json name

---

sdk/src/domain/context/account/MultiKey.ts
sdk/src/port/out/mirror/MirrorNodeAdapter.ts

fix: Add validation to check if a ProtobufEncoded key is a multikey

---

.github/actions/install-and-build/action.yaml
backend/package.json
cli/package.json
contracts/package.json
package-lock.json
package.json
sdk/package.json
web/package.json
web/src/components/ModalWalletConnect.tsx
web/src/components/ModalsHandler.tsx
web/src/layout/sidebar/Sidebar.tsx
web/src/views/MultiSigTransactions/MultisigTransactions.tsx
web/src/views/MultiSigTransactions/components/MultiSigTransactionModal.tsx
web/src/views/Operations/CheckKyc/index.tsx
web/src/views/Operations/DangerZone/index.tsx
web/src/views/Roles/GrantRoles.tsx
web/src/views/Roles/ManageCashIn.tsx
web/src/views/Roles/RevokeRoles.tsx
web/src/views/StableCoinCreation/Review.tsx
web/src/views/StableCoinCreation/StableCoinCreation.tsx

When trying to build Web module, it fails due to an import of parent dependencies that weren't updated in this [PR](https://github.com/hashgraph/stablecoin-studio/pull/1250).
**Checklist**

Fix @walletconnect/utils issue when building web

---

web/src/translations/en/stableCoinCreation.json
web/src/views/StableCoinCreation/ProofOfReserve.tsx
web/src/views/StableCoinCreation/Review.tsx
web/src/views/StableCoinCreation/StableCoinCreation.tsx
web/src/views/StableCoinCreation/__test__/__snapshots__/ProofOfReserve.test.tsx.snap

Add config ID and config version when proof of reserve is checked
Fixes #
**Checklist**

Fix: [BBND-926] Proof of reserve with config id and version

---

.github/workflows/publish.yaml
backend/package.json
changeVersion.sh
cli/package.json
contracts/package.json
package-lock.json
package.json
sdk/package.json
web/package.json

This PR modifiy publish.yml in order to fix the package creation of stablecoin-npm-contracts because the folder build is missing.
Fixes #1305 
Need to run ci pipeline to check that the package is properly published.
**Checklist**

fix: BBND-965 contracts pipeline

---

FACTORY_VERSION.md
RESOLVER_VERSION.md
backend/package.json
cli/package.json
contracts/README.md
contracts/package.json
package-lock.json
package.json
sdk/package.json
web/README.md
web/package.json

chore: update docs factory and resolver address

---

package-lock.json

fix: package updated

---

contracts/contracts/resolver/BusinessLogicResolver.sol
contracts/contracts/resolver/diamondCutManager/DiamondCutManager.sol
contracts/contracts/resolver/interfaces/diamondCutManager/IDiamondCutManager.sol

fix: no empty config or facets

---

contracts/contracts/resolver/BusinessLogicResolverWrapper.sol
contracts/contracts/resolver/interfaces/IBusinessLogicResolverWrapper.sol

fix: check if business logic address is 0
